/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDbHealthRouteImport } from './routes/api/db/health'
import { Route as ApiHealthConnectionRouteImport } from './routes/api/health/connection'
import { Route as ApiHealthStepsRouteImport } from './routes/api/health/steps'
import { Route as ApiHealthSummaryRouteImport } from './routes/api/health/summary'
import { Route as ApiSyncV1RunsSourceRunIdRouteImport } from './routes/api/sync/v1/runs/$sourceRunId'
import { Route as ApiSyncV1RunsSourceRunIdReceiptRouteImport } from './routes/api/sync/v1/runs/$sourceRunId/receipt'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbHealthRoute = ApiDbHealthRouteImport.update({
  id: '/api/db/health',
  path: '/api/db/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthConnectionRoute = ApiHealthConnectionRouteImport.update({
  id: '/api/health/connection',
  path: '/api/health/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthStepsRoute = ApiHealthStepsRouteImport.update({
  id: '/api/health/steps',
  path: '/api/health/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthSummaryRoute = ApiHealthSummaryRouteImport.update({
  id: '/api/health/summary',
  path: '/api/health/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncV1RunsSourceRunIdRoute =
  ApiSyncV1RunsSourceRunIdRouteImport.update({
    id: '/api/sync/v1/runs/$sourceRunId',
    path: '/api/sync/v1/runs/$sourceRunId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSyncV1RunsSourceRunIdReceiptRoute =
  ApiSyncV1RunsSourceRunIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => ApiSyncV1RunsSourceRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/health': typeof AppHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/health/connection': typeof ApiHealthConnectionRoute
  '/api/health/steps': typeof ApiHealthStepsRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/sync/v1/runs/$sourceRunId': typeof ApiSyncV1RunsSourceRunIdRouteWithChildren
  '/api/sync/v1/runs/$sourceRunId/receipt': typeof ApiSyncV1RunsSourceRunIdReceiptRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/health': typeof AppHealthRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/health/connection': typeof ApiHealthConnectionRoute
  '/api/health/steps': typeof ApiHealthStepsRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/sync/v1/runs/$sourceRunId': typeof ApiSyncV1RunsSourceRunIdRouteWithChildren
  '/api/sync/v1/runs/$sourceRunId/receipt': typeof ApiSyncV1RunsSourceRunIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/health/connection': typeof ApiHealthConnectionRoute
  '/api/health/steps': typeof ApiHealthStepsRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/sync/v1/runs/$sourceRunId': typeof ApiSyncV1RunsSourceRunIdRouteWithChildren
  '/api/sync/v1/runs/$sourceRunId/receipt': typeof ApiSyncV1RunsSourceRunIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/health'
    | '/api/auth/$'
    | '/api/db/health'
    | '/api/health/connection'
    | '/api/health/steps'
    | '/api/health/summary'
    | '/api/sync/v1/runs/$sourceRunId'
    | '/api/sync/v1/runs/$sourceRunId/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/health'
    | '/'
    | '/api/auth/$'
    | '/api/db/health'
    | '/api/health/connection'
    | '/api/health/steps'
    | '/api/health/summary'
    | '/api/sync/v1/runs/$sourceRunId'
    | '/api/sync/v1/runs/$sourceRunId/receipt'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/health'
    | '/_app/'
    | '/api/auth/$'
    | '/api/db/health'
    | '/api/health/connection'
    | '/api/health/steps'
    | '/api/health/summary'
    | '/api/sync/v1/runs/$sourceRunId'
    | '/api/sync/v1/runs/$sourceRunId/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDbHealthRoute: typeof ApiDbHealthRoute
  ApiHealthConnectionRoute: typeof ApiHealthConnectionRoute
  ApiHealthStepsRoute: typeof ApiHealthStepsRoute
  ApiHealthSummaryRoute: typeof ApiHealthSummaryRoute
  ApiSyncV1RunsSourceRunIdRoute: typeof ApiSyncV1RunsSourceRunIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/health': {
      id: '/api/db/health'
      path: '/api/db/health'
      fullPath: '/api/db/health'
      preLoaderRoute: typeof ApiDbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/connection': {
      id: '/api/health/connection'
      path: '/api/health/connection'
      fullPath: '/api/health/connection'
      preLoaderRoute: typeof ApiHealthConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/steps': {
      id: '/api/health/steps'
      path: '/api/health/steps'
      fullPath: '/api/health/steps'
      preLoaderRoute: typeof ApiHealthStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/summary': {
      id: '/api/health/summary'
      path: '/api/health/summary'
      fullPath: '/api/health/summary'
      preLoaderRoute: typeof ApiHealthSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/v1/runs/$sourceRunId': {
      id: '/api/sync/v1/runs/$sourceRunId'
      path: '/api/sync/v1/runs/$sourceRunId'
      fullPath: '/api/sync/v1/runs/$sourceRunId'
      preLoaderRoute: typeof ApiSyncV1RunsSourceRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/v1/runs/$sourceRunId/receipt': {
      id: '/api/sync/v1/runs/$sourceRunId/receipt'
      path: '/receipt'
      fullPath: '/api/sync/v1/runs/$sourceRunId/receipt'
      preLoaderRoute: typeof ApiSyncV1RunsSourceRunIdReceiptRouteImport
      parentRoute: typeof ApiSyncV1RunsSourceRunIdRoute
    }
  }
}

interface AppRouteChildren {
  AppHealthRoute: typeof AppHealthRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHealthRoute: AppHealthRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiSyncV1RunsSourceRunIdRouteChildren {
  ApiSyncV1RunsSourceRunIdReceiptRoute: typeof ApiSyncV1RunsSourceRunIdReceiptRoute
}

const ApiSyncV1RunsSourceRunIdRouteChildren: ApiSyncV1RunsSourceRunIdRouteChildren =
  {
    ApiSyncV1RunsSourceRunIdReceiptRoute: ApiSyncV1RunsSourceRunIdReceiptRoute,
  }

const ApiSyncV1RunsSourceRunIdRouteWithChildren =
  ApiSyncV1RunsSourceRunIdRoute._addFileChildren(
    ApiSyncV1RunsSourceRunIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDbHealthRoute: ApiDbHealthRoute,
  ApiHealthConnectionRoute: ApiHealthConnectionRoute,
  ApiHealthStepsRoute: ApiHealthStepsRoute,
  ApiHealthSummaryRoute: ApiHealthSummaryRoute,
  ApiSyncV1RunsSourceRunIdRoute: ApiSyncV1RunsSourceRunIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
